MODEL_NAME: breast_cancer_sim_exp
RADIOMICS_NAME: breast_cancer_bw_0.5
DOSES_DATASET_DIR: /workdir/bentrioum/database/radiopreditool/fccss/dose_matrix_full/
DOSES_DATASET_SUBDIRS:
    - CURIE
    - GR
    - TOULOUSE
    - REIMS
    - NICE
RESULTS_DIR: /workdir/bentrioum/results/radiopreditool/radiomics/
RADIOMICS_PARAMS_FILE: /gpfs/users/bentrioum/opt/radiopreditool/dose_matrix/radiomics/config/radiomics/radiomics_breast_cancer_bw_0.5.yaml
# Lung, heart, right breast, left breast, some active marrow
NAME_SUPER_T_FUNC: get_super_t_thorax
LABELS_SUPER_T_VOI: [1320, 1702, 2413, 3413, 2601]
LABELS_T_VOI: [309, 310, 413, 414, 415, 416, 417, 418, 419, 420]
FCCSS_CLINICAL_DATASET: /workdir/bentrioum/database/radiopreditool/fccss/base_fccss_igr_curie_011222_extended.csv.gz
FCCSS_CLINICAL_VARIABLES: []
EVENT_COL: "K2_loc20"
DATE_EVENT_COL: "date_K2_loc20"
NB_ESTIM_SCORE_MODELS: 5
N_BOOTSTRAP: 100
NAME_FILTER_DATASET: "women_sim_exp_censor_0.8_nsamples_1000"

