MODEL_NAME: pathol_cardiaque_grade3_drugs
RADIOMICS_NAME: 30X_32X_1320_1702
DOSES_DATASET_DIR: /workdir/bentrioum/database/radiopreditool/fccss/dose_matrix_full/
DOSES_DATASET_SUBDIRS:
    - CURIE
    - GR
    - TOULOUSE
    - REIMS
    - NICE
RESULTS_DIR: /workdir/bentrioum/results/radiopreditool/radiomics/
RADIOMICS_PARAMS_FILE: /gpfs/users/bentrioum/opt/radiopreditool/dose_matrix/radiomics/config/radiomics/radiomics_pathol_cardiaque.yaml
# 309 - 310: lung
# 320 - 324: heart
# 370 - 380: cerveau
# 413 - 420: breast 
# 702 - 704: thyroid
LABELS_SUPER_T_VOI: [1320, 1702]
LABELS_T_VOI: [309, 310, 320, 321, 322, 323, 324]
FCCSS_CLINICAL_DATASET: /workdir/bentrioum/database/radiopreditool/fccss/base_fccss_igr_curie_011021_extended.csv.gz
FCCSS_CLINICAL_VARIABLES: ["ALKYL", "ANTHRA"]
EVENT_COL: "Pathologie_cardiaque_3_new"
DATE_EVENT_COL: "date_pathol_cardiaque_3_new"
NB_ESTIM_SCORE_MODELS: 10

