MODEL_NAME: test_breast_cancer_bw_0.5
RADIOMICS_NAME: breast_cancer_bw_0.5
DOSES_DATASET_DIR: /Users/moud/Documents/RadioPrediTool/code/database/dose_matrix_sample/
DOSES_DATASET_SUBDIRS:
    - CURIE
    - GR
RESULTS_DIR: /Users/moud/Documents/RadioPrediTool/code/dose_matrix/radiomics/test/
RADIOMICS_PARAMS_FILE: /Users/moud/Documents/RadioPrediTool/code/dose_matrix/radiomics/config/radiomics/radiomics_breast_cancer_bw_0.5.yaml
# Lung, heart, right breast, left breast, some active marrow
NAME_SUPER_T_FUNC: get_super_t_active_marrow_subset
LABELS_SUPER_T_VOI: [1320, 1702, 2413, 3413, 2601]
LABELS_T_VOI: [309, 310]
FCCSS_CLINICAL_DATASET: /Users/moud/Documents/RadioPrediTool/code/database/fccss_01122022/base_fccss_igr_curie_011222_extended.csv.gz
FCCSS_CLINICAL_VARIABLES: ["categ_age_at_diagnosis", "ALKYL", "ANTHRA",
                           'iccc_10.b', 'iccc_03.d', 'iccc_03.e', 'iccc_09.b', 'iccc_11.b', 'iccc_09.d', 
                           'iccc_03.a', 'iccc_02.e', 'iccc_02.c', 'iccc_08.c', 'iccc_10.c', 'iccc_02.b', 
                           'iccc_03.c', 'iccc_08.a', 'iccc_03.b', 'iccc_02.a', 'iccc_09.a', 'iccc_05.a', 
                           'iccc_04.a', 'iccc_06.a']
EVENT_COL: "K2_loc20"
DATE_EVENT_COL: "date_K2_loc20"
NB_ESTIM_SCORE_MODELS: 5
N_BOOTSTRAP: 100
NAME_FILTER_DATASET: "women"

