DOSES_DATASET_DIR: /workdir/bentrioum/database/radiopreditool/fccss/dose_matrix_sample/
DOSES_DATASET_SUBDIRS:
    - Curie
    - GR
RESULTS_DIR: /workdir/bentrioum/results/radiopreditool/radiomics/
RADIOMICS_PARAMS_FILE: /gpfs/users/bentrioum/opt/radiopreditool/dose_matrix/radiomics/config/radiomics_pathol_cardiaque.yaml
LABELS_VOI_CSV_FILE: /workdir/bentrioum/database/radiopreditool/fccss/labels_organs_20160118.csv
VOI_TYPE: T
LABELS_VOI: [309, 310, 320, 321, 322, 323, 324]
FCCSS_CLINICAL_VARIABLES: []

