DOSES_DATASET_DIR: /workdir/bentrioum/database/radiopreditool/fccss/dose_matrix_full/
DOSES_DATASET_SUBDIRS:
    - Curie
    - GR
    - Toulouse
    - Reims
    - Nice
RESULTS_DIR: /workdir/bentrioum/results/radiopreditool/radiomics_T/
RADIOMICS_PARAMS_FILE: /gpfs/users/bentrioum/opt/radiopreditool/dose_matrix/radiomics/config/radiomics_pathol_cardiaque.yaml
LABELS_VOI_CSV_FILE: /workdir/bentrioum/database/radiopreditool/fccss/labels_organs_20160118.csv
VOI_TYPE: T
# 309 - 310: lung
# 320 - 324: heart
# 370 - 380: cerveau
# 413 - 420: breast 
# 702 - 704: thyroid
LABELS_VOI: [309, 310, 320, 321, 322, 323, 324, 413, 414, 415, 416, 417, 418, 419, 420, 702, 703, 704]
FCCSS_CLINICAL_DATASET: /workdir/bentrioum/database/radiopreditool/fccss/

