MODEL_NAME: pathol_cardiaque
DOSES_DATASET_DIR: /workdir/bentrioum/database/radiopreditool/fccss/dose_matrix_full/
DOSES_DATASET_SUBDIRS:
    - CURIE
    - GR
    - TOULOUSE
    - REIMS
    - NICE
RESULTS_DIR: /workdir/bentrioum/results/radiopreditool/radiomics/
RADIOMICS_PARAMS_FILE: /gpfs/users/bentrioum/opt/radiopreditool/dose_matrix/radiomics/config/radiomics_pathol_cardiaque.yaml
# 309 - 310: lung
# 320 - 324: heart
# 370 - 380: cerveau
# 413 - 420: breast 
# 702 - 704: thyroid
LABELS_T_VOI: [309, 310, 320, 321, 322, 323, 324, 413, 414, 415, 416, 417, 418, 419, 420, 702, 703, 704]
FCCSS_CLINICAL_DATASET: /workdir/bentrioum/database/radiopreditool/fccss/
FCCSS_CLINICAL_VARIABLES: ["chimiotherapie", "radiotherapie"]

